function dataStruct = MTR_importToStruct(filename)
%MTR_IMPORTTOSTRUCT Import an EnergyPlus output .mtr datafile to a struct.
%   dataStruct = ESO_importToStruct(filename)
%   Reads data from the file FILENAME to DATASTRUCT using the function
%   MTR_importFile.

%% Create struct from MTR_importFile output.
% get data values
[...
    Timestamp, ...
    ElectricityNetFacility, ...
    HeatingElectricity, ...
    HeatingGas, ...
    FansElectricity, ...
    InteriorLightsElectricity, ...
    WaterSystemsElectricity, ...
    ElectricityPurchasedFacility, ...
    ExteriorLightsElectricity, ...
    PumpsElectricity, ...
    ElectricityHVAC, ...
    GasFacility, ...
    GasHVAC, ...
    InteriorEquipmentElectricity, ...
    ElectricityFacility, ...
    WaterHeaterWaterSystemsElectricity, ...
    CoolingElectricity, ...
    ] ...
    = MTR_importFile(filename);
% convert E+ buildings demand: J to kWh
kwh = [...
    ElectricityNetFacility, ...
    HeatingElectricity, ...
    HeatingGas, ...
    FansElectricity, ...
    InteriorLightsElectricity, ...
    WaterSystemsElectricity, ...
    ElectricityPurchasedFacility, ...
    ExteriorLightsElectricity, ...
    PumpsElectricity, ...
    ElectricityHVAC, ...
    GasFacility, ...
    GasHVAC, ...
    InteriorEquipmentElectricity, ...
    ElectricityFacility, ...
    WaterHeaterWaterSystemsElectricity, ...
    CoolingElectricity, ...
    ] ...
    ./ 3600000;
% return struct
dataStruct = struct(...
    'Name',                                 filename(5:end-4),	...
    'Timestamp',                            Timestamp,          ...
    'ElectricityNetFacility',               kwh(:,1),           ...
    'HeatingElectricity',                   kwh(:,2),           ...
    'HeatingGas',                           kwh(:,3),           ...
    'FansElectricity',                      kwh(:,4),           ...
    'InteriorLightsElectricity',            kwh(:,5),           ...
    'WaterSystemsElectricity',              kwh(:,6),           ...
    'ElectricityPurchasedFacility',         kwh(:,7),           ...
    'ExteriorLightsElectricity',            kwh(:,8),           ...
    'PumpsElectricity',                     kwh(:,9),           ...
    'ElectricityHVAC',                      kwh(:,10),          ...
    'GasFacility',                          kwh(:,11),          ...
    'GasHVAC',                              kwh(:,12),          ...
    'InteriorEquipmentElectricity',         kwh(:,13),          ...
    'ElectricityFacility',                  kwh(:,14),          ...
    'WaterHeaterWaterSystemsElectricity',   kwh(:,15),          ...
    'CoolingElectricity',                   kwh(:,16)           ...
    );
end
