function newStruct = bldgInfoStruct()
%BLDGINFOSTRUCT New struct for adding building info.

newStruct = struct(...
    'area',{},          ...
    'equipment',{},     ...
    'lighting',{},      ...
    'occupancy',{},     ...
    'cool_setpt',{},    ...
    'heat_setpt',{}     ...
);

end
