function newStruct = newBldgStruct()
%BLDGINFOSTRUCT New struct for adding building info.

newStruct = struct(...
    'AirChangePerHr',       35,     ...
    'Area',                 [],     ...
    'Capacitance',          5,      ...
    'ColdAirSet',           12.8,	...
    'Comfort',              1.6667, ...
    'DPset',                11,     ...
    'DailyVariability',     0,      ...
    'HourlyVariability',    0,      ...
    'MinDamper',            0.2,	...
    'Name',                 [],     ...
    'Resistance',           880.92,	...
    'Schedule',             [],     ...
    'SubHourlyVariability', 0,      ...
    'Volume',               [],     ...
    'equipment',            [],     ...
    'lighting',             [],     ...
    'occupancy',            []      ...
);

newStruct.Schedule = struct(...
    'equipment',{},     ...
    'lighting',{},      ...
    'occupancy',{},     ...
    'cooling',{},       ...
    'heating',{}        ...
    );

end
