function sData = schedData(bType,param)
%SCHEDDATA Schedule for the given parameter for the given building type.
%   sData = schedData(bType,param)
%   Returns a cell array of alternating string-list pairs, with each pair
%   containing the name and times and values of a certain schedule.

switch bType
    case 'SmallHotel'
        switch param
            case 'equipment'
                sData = {...
                    'Corridor',         ''; ...
                    'Corridor4',        ''; ...
                    'Elec/MechRoom',    'HotelSmall BLDG_ELEVATORS';            ...
                    'ElevatorCore',     ''; ...
                    'ElevatorCore4',    ''; ...
                    'Exercise',         'HotelSmall ExerciseCenter_Eqp_Sch';    ...
                    'GuestLounge',      'HotelSmall Lobby_Eqp_Sch';             ...
                    'GuestRoom123Occ',  'HotelSmall GuestRoom_Eqp_Sch_Base';    ...
                    'GuestRoom123Vac',  'HotelSmall AlwaysOff';                 ...
                    'GuestRoom4Occ',    'HotelSmall GuestRoom_Eqp_Sch_Base';    ...
                    'GuestRoom4Vac',    'HotelSmall AlwaysOff';                 ...
                    'Laundry',          'HotelSmall LaundryRoom_Eqp_Elec_Sch';  ...
                    'Mechanical',       ''; ...
                    'Meeting',          'HotelSmall MeetingRoom_Eqp_Sch';       ...
                    'Office',           'HotelSmall OFF_EQUIP_SCH';             ...
                    'PublicRestroom',   ''; ...
                    'StaffLounge',      'HotelSmall EmployeeLounge_Eqp_Sch';    ...
                    'Stair',            ''; ...
                    'Stair4',           ''; ...
                    'Storage',          ''; ...
                    'Storage4Front',    ''; ...
                    'Storage4Rear',     ''; ...
                    };
            case 'lighting'
                sData = {...
                    'Corridor',         'HotelSmall BLDG_LIGHT_CORRIDOR_SCH';       ...
                    'Corridor4',        'HotelSmall BLDG_LIGHT_CORRIDOR_SCH';       ...
                    'Elec/MechRoom',    '';	...
                    'ElevatorCore',     ''; ...
                    'ElevatorCore4',    ''; ...
                    'Exercise',         'HotelSmall BLDG_LIGHT_EXERCENTER_SCH';     ...
                    'GuestLounge',      'HotelSmall BLDG_LIGHT_FRONTLOUNGE_SCH';    ...
                    'GuestRoom123Occ',  'BLDG_LIGHT_GUESTROOM_SCH_2010';            ...
                    'GuestRoom123Vac',  'HotelSmall AlwaysOff';                     ...
                    'GuestRoom4Occ',    'HotelSmall BLDG_LIGHT_GUESTROOM_SCH_2010'; ...
                    'GuestRoom4Vac',    'HotelSmall AlwaysOff';                     ...
                    'Laundry',          'HotelSmall BLDG_LIGHT_LAUNDRY_SCH';        ...
                    'Mechanical',       'HotelSmall BLDG_LIGHT_MECHROOM_SCH';       ...
                    'Meeting',          'HotelSmall BLDG_LIGHT_MEETINGROOM_SCH';    ...
                    'Office',           'HotelSmall BLDG_LIGHT_OFFICE_SCH';         ...
                    'PublicRestroom',   'HotelSmall BLDG_LIGHT_RESTROOM_SCH';       ...
                    'StaffLounge',      'HotelSmall BLDG_LIGHT_EMPLOYEELOUNGE_SCH'; ...
                    'Stair',            'HotelSmall BLDG_LIGHT_STAIR_SCH';          ...
                    'Stair4',           'HotelSmall BLDG_LIGHT_STAIR_SCH';          ...
                    'Storage',          'HotelSmall BLDG_LIGHT_STORAGE_SCH';        ...
                    'Storage4Front',    'HotelSmall BLDG_LIGHT_STORAGE_SCH';        ...
                    'Storage4Rear',     'HotelSmall BLDG_LIGHT_STORAGE_SCH';        ...
                    };
            case 'occupancy'
                sData = {...
                    
                    };
            otherwise
                error(strcat('Parameter %s not recognized for', ...
                    ' building type %s.'), param, bType)
        end
    otherwise
        error('Building type %s not recognized.', bType)
end

end
